// Read the live squad straight out of fm.exe. No Cheat Engine, no manual step.
//
// WHY
// pick_lineup.js reads data/snapshots/squad.json -- a file a human had to produce
// by driving Cheat Engine's GUI (locate_vector() plus a ~2 minute scan). A
// decision loop cannot depend on that. This produces the same JSON, live, from a
// script.
//
// HOW IT FINDS THE PLAYERS
// A player record holds Row ID at +0x278 and UID at +0x27C -- ADJACENT. Together
// they make an 8-byte signature that is effectively unique, where a bare 4-byte
// UID returns hundreds of coincidental hits. Record base = hit - 0x278.
//
// The Row IDs and UIDs come from data/roster/*.json. They are GAME data: identical
// across restarts, unlike every address in the process. That is what makes this
// work from cold with nothing hardcoded.
//
// All 23 signatures are searched in ONE pass by scripts/win/scan_mem.ps1, so
// finding the whole squad costs about what finding one player used to.
//
// FIELD OFFSETS ARE NEVER HAND-COPIED. They come from cheat-table/fields.json,
// generated by cheat-table/parse_ct.js from the vendored table. Hand-copying
// offsets is what produced the reversed-offset bug that silently nil-ed every
// name and contract field (docs/phase1-notes.md).
//
//   node scripts/manager/read_squad.js
//   node scripts/manager/read_squad.js --out data/snapshots/squad_live.json
//   node scripts/manager/read_squad.js --roster data/roster/aston-villa.json

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..', '..');
const PS = 'powershell.exe';
const SCAN = path.join(REPO, 'scripts', 'win', 'scan_mem.ps1');
const DUMP_MANY = path.join(REPO, 'scripts', 'win', 'dump_many.ps1');
const TMP = path.join(REPO, 'data', 'snapshots');

const ROWID_OFF = 0x278;      // Row ID, 4 bytes
const UID_OFF   = 0x27C;      // UID,    4 bytes -- adjacent, hence the 8-byte signature
const RECORD_LEN = 0x400;     // covers every single-offset field in fields.json

// -ExecutionPolicy Bypass: the machine blocks .ps1 files. Per-child override only;
// it changes no machine or user setting.
function ps(script, args) {
  return execFileSync(PS,
    ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', script, ...args],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
}

const readJson = p => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^﻿/, ''));

const hex = n => n.toString(16).toUpperCase();
const leBytes = (v, n) => {
  const out = [];
  for (let i = 0; i < n; i++) out.push(((v >>> (i * 8)) & 0xFF).toString(16).padStart(2, '0').toUpperCase());
  return out;
};

function dumpMany(items, len, tag) {
  if (!items.length) return {};
  const spec = path.join(TMP, 'rs_spec_' + tag + '.json');
  const out = path.join(TMP, 'rs_dump_' + tag + '.json');
  fs.writeFileSync(spec, JSON.stringify(items));
  ps(DUMP_MANY, ['-Spec', spec, '-Length', String(len), '-Out', out]);
  const raw = readJson(out);
  const by = {};
  for (const r of raw.rows) {
    const arr = Array.isArray(r.bytes) ? r.bytes : (r.bytes && r.bytes.value) || [];
    by[r.label] = Buffer.from(arr);
  }
  return by;
}

// ------------------------------------------------------------------ field decode
// Decode every field whose offsets are a single value inside the record window.
// Multi-level chains (names, contract, club) are followed separately below.

function loadFieldDefs() {
  const f = readJson(path.join(REPO, 'cheat-table', 'fields.json'));
  const single = [];
  const chains = [];
  for (const x of f['Current Player']) {
    const offs = x.offsets.map(o => parseInt(o, 16));
    if (offs.length === 1) {
      if (offs[0] + 8 <= RECORD_LEN) single.push({ path: x.path, off: offs[0], type: x.varType });
    } else {
      chains.push({ path: x.path, offs, type: x.varType });
    }
  }
  return { single, chains };
}

function readTyped(buf, off, type) {
  switch (type) {
    case 'Byte':    return off + 1 <= buf.length ? buf.readUInt8(off) : null;
    case '2 Bytes': return off + 2 <= buf.length ? buf.readUInt16LE(off) : null;
    case '4 Bytes': return off + 4 <= buf.length ? buf.readUInt32LE(off) : null;
    case '8 Bytes': return off + 8 <= buf.length ? Number(buf.readBigUInt64LE(off)) : null;
    default:        return null;
  }
}

function setPath(obj, p, value) {
  let cur = obj;
  for (let i = 0; i < p.length - 1; i++) {
    if (!cur[p[i]] || typeof cur[p[i]] !== 'object') cur[p[i]] = {};
    cur = cur[p[i]];
  }
  cur[p[p.length - 1]] = value;
}

// Player-record strings are plain zero-terminated single-byte buffers
// (fm.CT has Unicode=0 -- see docs/phase1-notes.md). NOTE this is the opposite of
// the selection-list records, whose strings are LENGTH-PREFIXED.
function readCString(buf, off, max = 64) {
  let end = off;
  while (end < buf.length && end - off < max && buf[end] !== 0) end++;
  return end > off ? buf.slice(off, end).toString('utf8') : null;
}

// ------------------------------------------------------------------ main

function main() {
  const argv = process.argv.slice(2);
  const rosterPath = argv.includes('--roster')
    ? argv[argv.indexOf('--roster') + 1]
    : path.join(REPO, 'data', 'roster', 'aston-villa.json');
  const outPath = argv.includes('--out')
    ? path.resolve(REPO, argv[argv.indexOf('--out') + 1])
    : path.join(TMP, 'squad_live.json');

  const roster = readJson(rosterPath);
  const players = roster.players.filter(p => p.uid && p.rowId !== undefined);
  if (!players.length) {
    console.error('roster has no rowId values -- regenerate it (see docs); a bare UID\n' +
                  'is too weak a signature and returns hundreds of false hits.');
    process.exit(2);
  }
  console.log(`roster: ${roster.club}, ${players.length} players`);

  // 1. One scan for all 23 Row ID + UID signatures.
  const patFile = path.join(TMP, 'rs_patterns.json');
  fs.writeFileSync(patFile, JSON.stringify(players.map(p => ({
    label: String(p.uid),
    pattern: [...leBytes(p.rowId, 4), ...leBytes(p.uid, 4)].join(' '),
  }))));
  const hitsFile = path.join(TMP, 'rs_hits.json');
  const scanOut = ps(SCAN, ['-PatternFile', patFile, '-Out', hitsFile, '-Max', '40']);
  console.log('  ' + scanOut.trim().split(/\r?\n/)[0]);
  const byLabel = readJson(hitsFile).byLabel || {};

  // 2. Dump a record window from every candidate base.
  const cands = [];
  for (const p of players) {
    for (const h of (byLabel[String(p.uid)] || [])) {
      cands.push({ label: p.uid + '@' + h, addr: hex(parseInt(h, 16) - ROWID_OFF), uid: p.uid });
    }
  }
  if (!cands.length) {
    console.error('no player records found -- is the right save loaded?');
    process.exit(3);
  }
  const recs = dumpMany(cands.map(c => ({ label: c.label, addr: c.addr })), RECORD_LEN, 'rec');

  // 3. Validate. The signature already pins identity; this rejects coincidental
  //    matches by checking the record is internally sane.
  const { single, chains } = loadFieldDefs();
  const chosen = new Map();
  for (const c of cands) {
    const buf = recs[c.label];
    if (!buf || buf.length < RECORD_LEN) continue;
    if (buf.readUInt32LE(UID_OFF) !== c.uid) continue;
    const ca = buf.readUInt16LE(0x1FC), pa = buf.readUInt16LE(0x1FE);
    if (!(ca >= 1 && ca <= 200 && pa >= 1 && pa <= 200 && ca <= pa)) continue;
    let posOk = true;
    for (let o = 0x204; o <= 0x212; o++) { const v = buf[o]; if (v < 1 || v > 20) { posOk = false; break; } }
    if (!posOk) continue;
    if (!chosen.has(c.uid)) chosen.set(c.uid, { base: parseInt(c.addr, 16), buf });
  }
  console.log(`  validated ${chosen.size}/${players.length} player records`);

  // 4. Follow the pointer chains, generically.
  //
  // Resolution semantics (docs/phase1-notes.md, confirmed against live memory):
  // for offsets [o0..on] the address is `base + o0`, then `[addr] + oi` for each
  // subsequent offset, and the value is read at the final address with no
  // trailing dereference. So n offsets means n-1 pointer reads.
  //
  // Chain depth VARIES -- Contract is [338,18] (1 deref), names are [2c8,0,4]
  // (2), and Team Club is [88,30,b8,4] (3). Hardcoding a depth crashes on the
  // deeper ones, so walk level by level and batch each level in one call.
  const live = [];
  for (const [uid, r] of chosen) {
    for (const ch of chains) {
      live.push({
        label: uid + '|' + ch.path.join('/'),
        uid, ch,
        addr: r.base + ch.offs[0],
        level: 1,
      });
    }
  }

  const maxLevels = Math.max(...chains.map(c => c.offs.length));
  for (let lvl = 1; lvl < maxLevels; lvl++) {
    const todo = live.filter(x => x.level === lvl && x.addr > 0x10000 && x.ch.offs.length > lvl);
    if (!todo.length) continue;
    const got = dumpMany(todo.map(x => ({ label: x.label, addr: hex(x.addr) })), 8, 'lvl' + lvl);
    for (const x of todo) {
      const b = got[x.label];
      const ptr = b && b.length >= 8 ? Number(b.readBigUInt64LE(0)) : 0;
      x.addr = ptr > 0x10000 ? ptr + x.ch.offs[lvl] : 0;
      x.level = lvl + 1;
    }
  }

  // Final read at the resolved address, no further dereference.
  const finals = live.filter(x => x.addr > 0x10000);
  const finalBuf = dumpMany(finals.map(x => ({ label: x.label, addr: hex(x.addr) })), 0x40, 'final');
  const chainValue = new Map();
  for (const x of finals) {
    const b = finalBuf[x.label];
    if (!b || !b.length) continue;
    chainValue.set(x.label, x.ch.type === 'String' ? readCString(b, 0) : readTyped(b, 0, x.ch.type));
  }

  // 5. Assemble, in exactly the shape scripts/manager/squad_state.js expects.
  const out = [];
  for (const p of players) {
    const r = chosen.get(p.uid);
    if (!r) { console.warn(`  ! ${p.first} ${p.last} not found in memory`); continue; }
    const rec = {};
    for (const f of single) setPath(rec, f.path, readTyped(r.buf, f.off, f.type));

    for (const ch of chains) {
      const v = chainValue.get(p.uid + '|' + ch.path.join('/'));
      if (v !== undefined) setPath(rec, ch.path, v);
    }
    setPath(rec, ['_', 'Dont touch', 'pPlayer'], r.base);
    out.push(rec);
  }

  const doc = {
    squad_source: 'read_squad.js (live, CE-free)',
    squad_array: null,
    squad_count: out.length,
    read_at: new Date().toISOString(),
    players: out,
  };
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(doc, null, 1));

  console.log(`\nwrote ${path.relative(REPO, outPath)} -- ${out.length} players`);
  for (const q of out.slice(0, 5)) {
    const n = (q['Player Info'] || {})['Name (Read Only)'] || {};
    const a = q.Attributes || {}, o = q.Other || {};
    console.log(`  ${((n['First Name'] || '') + ' ' + (n['Last Name'] || '')).trim().padEnd(26)}` +
                ` CA=${String(a.CA).padStart(3)} PA=${String(a.PA).padStart(3)}` +
                ` cond=${o.Condition} fit=${o.Fitness}`);
  }
}

main();
